---
- name: Install terraform from Internet
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  become: yes
- name: Install terragrunt from Internet
  get_url:
    url: https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64
    dest: /usr/local/bin/terragrunt
    mode: 0755
  become: yes
