---
- name: Install terraform from Internet
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  become: yes
- name: Install terragrunt from Internet
  get_url:
    url: https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64
    dest: /usr/local/bin/terragrunt
    mode: 0755
    force: yes
  become: yes

- name: Install custom smallutil provider
  block:
    - name: Create terraform provider directory
      file:
        path: "{{ ansible_env.HOME }}/.terraform.d/plugins/github.com/guangie88/smallutil/0.4.1/linux_amd64"
        state: directory
    - name: Download provider binary
      unarchive:
        src: https://github.com/guangie88/terraform-provider-smallutil/releases/download/v0.4.1/terraform-provider-smallutil_linux_amd64_v0.4.1.zip
        dest: "{{ ansible_env.HOME }}/.terraform.d/plugins/github.com/guangie88/smallutil/0.4.1/linux_amd64"
        remote_src: yes

- name: Install custom patched local provider
  block:
    - name: Create terraform provider directory
      file:
        path: "{{ ansible_env.HOME }}/.terraform.d/plugins/registry.terraform.io/dsaidgovsg/local/2.0.1-pre.0/linux_amd64"
        state: directory
    - name: Download provider binary
      get_url:
        url: https://github.com/dsaidgovsg/terraform-provider-local/releases/download/v2.0.1-patch.0/terraform-provider-local_linux_amd64
        dest: "{{ ansible_env.HOME }}/.terraform.d/plugins/registry.terraform.io/dsaidgovsg/local/2.0.1-pre.0/linux_amd64/terraform-provider-local"
        mode: 0550
