---
- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: ~/get-helm.sh
    mode: 0700
- name: Install helm
  command: ~/get-helm.sh
- name: Delete install script
  file:
    path: ~/get-helm.sh
    state: absent
