---
- name: Download Helm client archive
  get_url:
    url: https://github.com/helm/helm/releases/download/v{{ helm_version }}/helm-v{{ helm_version }}-linux-amd64.tar.gz.asc
    dest: /tmp/helm-client-linux-amd64.tar.gz
    checksum: sha256:https://github.com/helm/helm/releases/download/v{{ helm_version }}/helm-v{{ helm_version }}-linux-amd64.tar.gz.sha256.asc
- name: Extract helm from archive
  unarchive:
    src: /tmp/helm-client-linux-amd64.tar.gz
    dest: /usr/local/bin/
    mode: 0755
  become: yes
- name: Delete downloaded archive
  file:
    path: /tmp/helm-client-linux-amd64.tar.gz
    state: absent
