---
- name: Install required dependencies
  block:
    - name: From dnf
      dnf:
        name:
          - unzip
        state: latest
      become: yes
    - name: From pip
      pip:
        name: setuptools==50
      become: yes
- name: Install nice-to-have dependencies from dnf
  dnf:
    name:
      - vim
    state: latest
  become: yes
