---
- name: Install required dependencies
  block:
    - name: From dnf
      dnf:
        name:
          - jq
          - unzip
        state: latest
      become: yes
    - name: From pip
      pip:
        name: setuptools==50
        umask: "0022"
      become: yes
- name: Install nice-to-have dependencies from dnf
  dnf:
    name:
      - vim
    state: latest
  become: yes
