---
- name: Add EPEL repository
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
  become: yes
- name: Install the_silver_searcher
  yum:
    name:
      - the_silver_searcher
    state: present
  become: yes
- name: Install required dependencies
  block:
    - name: From dnf
      dnf:
        name:
          - jq
          - socat
          - unzip
          - wget
          - htop
        state: latest
      become: yes
    - name: From pip
      pip:
        name:
          - netaddr
          - setuptools
          - boto3
          - trash-cli
        umask: "0022"
      become: yes
- name: Install nice-to-have dependencies from dnf
  dnf:
    name:
      - vim
    state: latest
  become: yes
