---
- name: Install required dependencies from dnf
  dnf:
    name:
      - unzip
    state: latest
  become: yes
- name: Install nice-to-have dependencies from dnf
  dnf:
    name:
      - vim
    state: latest
  become: yes
# Because Ansible pip action needs setuptools, and setuptools needs pip to
# install, we break the chicken-and-egg issue by running the pip raw
# Running pip install raw is always regarded as a "change"
- name: Install setuptools via raw pip
  shell: pip install --no-cache-dir setuptools==50
