# pip is broken for Python3 at the moment, keeps giving
# fatal: [localhost]: FAILED! => {"changed": false, "msg": "No setuptools found in remote host, please install it first."}
# - name: Install awscli via pip
#   pip:
#     name: awscli=={{ awscli_version }}
# Running pip install raw is always regarded as a "change"
- name: Install awscli via raw pip install
  shell: pip install --no-cache-dir awscli=={{ awscli_version }}
