---
- name: Download tmux
  get_url:
    url: https://github.com/nelsonenzo/tmux-appimage/releases/download/tmux3.1b/tmux-3.1b-x86_64.AppImage
    dest: /usr/local/bin/tmux
    mode: 0755
    force: yes
  become: yes
# https://github.com/AppImage/AppImageKit/wiki/FUSE
# https://bugzilla.redhat.com/show_bug.cgi?id=1758884
≤- name: Install FUSE
  block:
    - name: From dnf
      dnf:
        name:
          - fuse
        state: latest
      become: yes
