---
- name: Set up true jumphost
  hosts: all
  vars: 
    terraform_version: 0.12.24
    terragrunt_version: 0.22.5
    consul_version: 1.8.3
    nomad_version: 0.12.4
    vault_version: 1.3.10  # We don't use >= 1.4 for now due to Terraform provider issues
    packer_version: 1.6.2
  tasks:
  - name: Install common set of prequisites
    include_role:
      name: "{{ playbook_dir }}/roles/common"
  - name: Install terraform and terragrunt
    include_role:
      name: "{{ playbook_dir }}/roles/terraform"
  - name: Install consul
    include_role:
      name: "{{ playbook_dir }}/roles/consul"
  - name: Install nomad
    include_role:
      name: "{{ playbook_dir }}/roles/nomad"
  - name: Install vault
    include_role:
      name: "{{ playbook_dir }}/roles/vault"
  - name: Install packer
    include_role:
      name: "{{ playbook_dir }}/roles/packer"
