---
- name: Set up true jumphost
  hosts: all
  vars: 
    terraform_version: 0.13.6
    terragrunt_version: 0.26.0
    docker_version: 19.03.13
    consul_version: 1.9.2
    nomad_version: 1.0.2
    vault_version: 1.5.4
    packer_version: 1.6.5
    awscli_version: 1.18.137
    awless_version: 0.1.11
    cfssl_version: 1.4.1
    kubectl_version: 1.19.4
    allow_convenience: true
    allow_emacs: false
  tasks:
  - name: Install common set of prequisites
    include_role:
      name: "{{ playbook_dir }}/roles/common"
  - name: Install Docker
    include_role:
      name: "{{ playbook_dir }}/roles/docker"
  - name: Install Terraform and Terragrunt
    include_role:
      name: "{{ playbook_dir }}/roles/terraform"
  - name: Install Consul
    include_role:
      name: "{{ playbook_dir }}/roles/consul"
  - name: Install Nomad
    include_role:
      name: "{{ playbook_dir }}/roles/nomad"
  - name: Install Vault
    include_role:
      name: "{{ playbook_dir }}/roles/vault"
  - name: Install Packer
    include_role:
      name: "{{ playbook_dir }}/roles/packer"
  - name: Install awscli
    include_role:
      name: "{{ playbook_dir }}/roles/awscli"
  - name: Install awless
    include_role:
      name: "{{ playbook_dir }}/roles/awless"
  - name: Install cfssl
    include_role:
      name: "{{ playbook_dir }}/roles/cfssl"
  - name: Install kubectl
    include_role:
      name: "{{ playbook_dir }}/roles/kubectl"
  - name: Install openvpn
    include_role:
      name: "{{ playbook_dir }}/roles/openvpn"
  - name: Install psql
    include_role:
      name: "{{ playbook_dir }}/roles/psql"
  - name: Install tmux
    include_role:
      name: "{{ playbook_dir }}/roles/tmux"
  - name: Allow convenience features
    include_role:
      name: "{{ playbook_dir }}/roles/convenience"
    when: allow_convenience | bool
  - name: Allow emacs
    include_role:
      name: "{{ playbook_dir }}/roles/emacs"
    when: allow_emacs | bool
