---
- name: Install emacs
  block:
    - name: From dnf
      dnf:
        name:
          - emacs
        state: latest
      become: yes
- name: Install spacemacs config
  get_url:
    url: https://github.com/syl20bnr/spacemacs
    dest: ../.emacs.d
    mode: 0755
    force: yes
  become: yes
