name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  draft-release:
    runs-on: ubuntu-20.04
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
